name: test matrix job

on:
  workflow_dispatch: 
  
jobs:

  approve-and-auth:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      azure-creds: ${{ steps.out.outputs.creds }}
    steps:
      - id: login
        name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: set output
        id: out
        run: |
          echo "creds=$(az account get-access-token --query accessToken -o tsv)" >> $GITHUB_OUTPUT

  deploy-matrix:
    needs: [approve-and-auth]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ 1,2,3 ]
    steps:
      - name: Azure Login from shared credentials
        uses: azure/login@v2
        with:
          creds: ${{ needs.approve-and-auth.outputs.azure-creds }}

      - name: Deploy ${{ matrix.component }}
        run: |
          echo running step ${{ matrix.component }}
