name: test template
on:
  repository_dispatch:
    types: [test-template]
  workflow_call: 

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test1 - step1
        run: echo "running test1 step1"

      - name: test1 - step2
        run: echo "running test1 step2"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: test2-step1
        run: echo "running test 2 step1"

      - name: test2-step2
        run: echo "running test 2 step 2"

  test3:
    uses: dpdeepankar/GithubActionsTest/.github/workflows/template-test2.yml@main

      

        
  
