name: test1

on:
  push:
    branches:
      - dlv
      - acc
      
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: test
        run: echo "$TEMP_VAR"
  
