name: test workflow

on:
  push:
    branches: 
     - feature1
    paths: 
     - .github/wprkflows/test-workflow.yaml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "test run"
